[package]
name = "ira"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scratch-parser = { path = "./scratch-parser" }
scratch-loader = { path = "./scratch-loader" }
colored = "2.0.0"
